<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/AdminMaster.Master" CodeBehind="AdminAssets.aspx.vb" Inherits="UdupiElectricityBoard.AdminAssets" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        input[type="text"]{
            border-radius:8px;
            padding:5px;
            margin:10px;
            outline:none;
            width:180px;
        }
        input[type=submit]{
            margin:auto;
            text-align:center;
            border-radius:8px;
            background-color:red;
            padding:5px 50px;
        }
        input[type=submit]:hover{
            background-color:rgb(173, 12, 20);
        }
        .add{
            margin: 20px auto;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <form runat="server">
        <asp:Panel runat="server">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSourceAssets" Font-Bold="True" Font-Size="X-Large" CellPadding="4" ForeColor="#333333" GridLines="None" Width="1550px" Height="200px" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" DataKeyNames="Assets"> 
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="Assets" HeaderText="Assets" SortExpression="Assets" ControlStyle-Width="150px" ReadOnly="True" />
                    <asp:BoundField DataField="Total" HeaderText="Total" SortExpression="Total" ControlStyle-Width="150px" />
                    <asp:BoundField DataField="In_Use" HeaderText="In_Use" SortExpression="In_Use" ControlStyle-Width="150px"/>
                    <asp:BoundField DataField="Active" HeaderText="Active" SortExpression="Active" ControlStyle-Width="150px"/>
                    <asp:BoundField DataField="InActive" HeaderText="InActive" SortExpression="InActive" ControlStyle-Width="150px"/>
                    <asp:BoundField DataField="Username" HeaderText="Username" SortExpression="Username" ControlStyle-Width="150px"/>
                </Columns>
                <EditRowStyle BackColor="#2461BF" Font-Size="X-Large" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSourceAssets" runat="server" ConnectionString="<%$ ConnectionStrings:UEBConnectionString2 %>" SelectCommand="SELECT * FROM [tblAssets]"
                UpdateCommand="UPDATE tblAssets SET Assets =@Assets, Total =@Total, In_Use =@In_Use, Active =@Active, Username =@Username, InActive =@InActive WHERE Assets=@Assets"
                DeleteCommand="DELETE FROM tblAssets WHERE [Assets]=@Assets">
                <UpdateParameters>
                    <asp:Parameter Name="Assets"></asp:Parameter>
                    <asp:Parameter Name="Total"></asp:Parameter>
                    <asp:Parameter Name="In_Use"></asp:Parameter>
                    <asp:Parameter Name="Active"></asp:Parameter>
                    <asp:Parameter Name="Username"></asp:Parameter>
                    <asp:Parameter Name="InActive"></asp:Parameter>
                </UpdateParameters>
                <DeleteParameters>
                    <asp:Parameter Name="Assets" />
                </DeleteParameters>
            </asp:SqlDataSource>
<%--            <div class="delete">
                <input id="delAsset" name="Assets" runat="server" placeholder="Asset" type="text" pattern="[A-Za-z]{,18}" title="Only 18 characters"/>
                 <input type="submit" runat="server" value="Delete" onserverclick =" Del" />
            </div>--%>
            <div class="add">
            <input id="Assets" name="Assets" runat="server" placeholder="Asset" type="text" pattern="[A-Za-z]{,18}" title="Only 18 characters"/>
            <input id="Total" name="Total" runat="server" placeholder="Total" type="text" pattern="[0-9]{6)" title="Only 6 digits"/>
            <input id="In_Use" name="In_Use" runat="server" placeholder="In Use" type="text" pattern="[0-9]{6)" title="Only 6 digits"/>
            <input id="Active" name="Active" runat="server" placeholder="Active" type="text" pattern="[0-9]{6)" title="Only 6 digits"/>
            <input id="InActive" name="InActive" runat="server" placeholder="InActive" type="text" pattern="[0-9]{6)" title="Only 6 digits"/>
            <input id="Username" name="Username" runat="server" placeholder="Username" type="text" pattern="[A-Za-z]{,18}" title="Only 18 characters"/>
            <input type="submit" runat="server" value="Add" onserverclick =" Add" />
            </div>                   
        </asp:Panel>

    </form>
</asp:Content>
