<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/AdminMaster.Master" CodeBehind="AdminNews.aspx.vb" Inherits="UdupiElectricityBoard.AdminNews" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        .Feedback {
            display: block;
            width: 800px;
            padding: 20px;
            margin: 30px auto;
        }

        .btn {
            display: block;
            margin: auto;
        }

        #form1 {
            margin: auto;
        }

        .Name {
            display: block;
            margin: auto;
            width: 220px;
            border-radius: 5px;
            outline: none;
            margin-top: 20px;
            padding: 8px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="title-heading-w3 text-center mx-auto">
        <h3 class="title-big">News Updates</h3>
    </div>
    <form id="form1" runat="server">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" HorizontalAlign="Center" Width="90%" >
        <Columns>
            <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
            <asp:BoundField DataField="News" HeaderText="News" SortExpression="News" />
            <asp:BoundField DataField="Username" HeaderText="Username" SortExpression="Username" />
            <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
        </Columns>
    </asp:GridView>
    
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:UEBConnectionString22 %>" SelectCommand="SELECT * FROM [tblNews]"  DeleteCommand ="DELETE FROM [tblNews] WHERE [Date] = @Date">
          <DeleteParameters>
              <asp:Parameter Name="Date" />
          </DeleteParameters>
            
        </asp:SqlDataSource>
        <input type="text" id="Name" class="Name" runat="server" placeholder="Your Name" />
        <input type="text" id="NTitle" class="Name" runat="server" placeholder="News Title" />
        <textarea style="resize:none;" runat="server" placeholder="New news feed" class="Feedback" id="News" rows="5" cols="100" required=""></textarea>
        <input runat="server" type="submit" value="Submit" class="btn btn-primary btn-style" onserverclick="Submit"/>
    </form>
</asp:Content>
