'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustSignup

    '''<summary>
    '''Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Email As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Phone As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Aadhar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Aadhar As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Address As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''RR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RR As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Cno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cno As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''SubDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubDiv As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Lcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lcode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Mcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mcode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Uname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Uname As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Password As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''Cpassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cpassword As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''Question control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Question As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Answer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Answer As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit As Global.System.Web.UI.HtmlControls.HtmlInputSubmit
End Class
